# Generated by Django 4.1.13 on 2024-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
