# Generated by Django 4.1.13 on 2024-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
