# Generated by Django 4.1.13 on 2024-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_product',
            field=models.CharField(default='book', max_length=50),
        ),
    ]
