# Generated by Django 4.1.13 on 2024-05-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiate_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='init_payment',
        ),
    ]
