# Generated by Django 4.1.13 on 2024-04-17 09:16

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clothes_type',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.BigIntegerField()),
                ('type', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.type')),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
    ]
