# Generated by Django 4.1.13 on 2024-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_producer_style_remove_clothes_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='type_product',
            field=models.CharField(default='close', max_length=50),
        ),
    ]
