services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=order
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data:
  mongodb_data:
