# Generated by Django 4.1.13 on 2024-04-19 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.type'),
        ),
    ]
