# Generated by Django 4.1.13 on 2024-04-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_mobile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
