# Generated by Django 4.1.13 on 2024-05-08 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status_id', models.PositiveBigIntegerField()),
                ('user_id', models.PositiveBigIntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), size=None)),
                ('products_type', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipment_updates',
            },
        ),
    ]
